### ISSUE TITLE
Add a simple calculator

### ISSUE THREAD

**Issue by Sanket1308** [codemistic/General-Projects#116]
![Screenshot (1112)](https://user-images.githubusercontent.com/79108273/194701560-672e40cf-ef47-401d-940f-cb7469c4f630.png)

**Comment by Sanket1308** [comment]
@TKirtan Kindly assign me this under hacktoberfest

**Comment by Sengar123** [comment]
Hello Sir,
Kindly assign this task to me.I want to solve this issue.

**Comment by hackbysarthak03** [comment]
Please Assign this to me as I have built this as one of my project. So it can be added Simply.

**Comment by Sanket1308** [comment]
Thank you for assigning me. I am starting to work on it now.
